name: Deploy Food Order App On AWS Elastic Beanstalk
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t raghava1/food-order-app-test -f ./Dockerfile.dev ./
      - run: docker run -e CI=true raghava1/food-order-app-test npm test

      - run: docker build -t raghava1/food-order-app-prod ./
      - run: docker push raghava1/food-order-app-prod

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: Raghava-Chittidi/Food-Order-App
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: RaghavaDockerEBS
          environment_name: RaghavaDockerEBS-env
          existing_bucket_name: elasticbeanstalk-ap-southeast-1-986306805738
          region: ap-southeast-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
